# makefile for BagTester using ArrayBag
BagTester.exe: BagTester.o 
	g++ -std=gnu++11 -o BagTester.exe BagTester.o 
BagTester.o: BagTester.cpp ArrayBag.cpp ArrayBag.h BagInterface.h
	g++ -std=gnu++11 -g -c BagTester.cpp


	
	
	